name = ""
type = "javascript"
compatibility_date = "2021-12-06"

zone_id = ""
account_id = "b6eea3288d32ee67f535ce4e6fe9dfef"
route = ""
workers_dev = true

[[kv_namespaces]]
binding = "CONTENT"
preview_id = "c89209108caa478ab46af72f8db8a17f"
id = "c89209108caa478ab46af72f8db8a17f"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"

[miniflare]
kv_persist = true